name: Build & Release (.NET 8)
run-name: Release ${{ github.ref_name }}

env:
    CONFIGURATION: Release
    DOTNET_VERSION: 8.0.x

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CSPracticePlugin/CSPracticePlugin.csproj

      - name: Build (Release)
        run: |
          dotnet build CSPracticePlugin/CSPracticePlugin.csproj \
            --configuration Release \
            --no-restore

      - name: Collect DLL
        run: |
          mkdir -p artifact
          mkdir -p artifact/addons
          mkdir -p artifact/addons/counterstrikesharp
          mkdir -p artifact/addons/counterstrikesharp/plugins
          mkdir -p artifact/addons/counterstrikesharp/plugins/CSPracticePlugin
          cp CSPracticePlugin/bin/Release/net8.0/CSPracticePlugin.dll \
            artifact/addons/counterstrikesharp/plugins/CSPracticePlugin/
          cp CSPracticePlugin/bin/Release/net8.0/CSPracticePlugin.pdb \
          artifact/addons/counterstrikesharp/plugins/CSPracticePlugin/ || true

      - name: Zip release artifact
        run: |
          cd artifact
          zip -r ../CSPracticePlugin-${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: CSPracticePlugin-${{ github.ref_name }}.zip