name: Build & Release (.NET 8)

env:
    CONFIGURATION: Release
    DOTNET_VERSION: 8.0.x

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $CsSpawnsPlugin/CsSpawnsPlugin.csproj

      - name: Build (Release)
        run: |
          dotnet build $CsSpawnsPlugin/CsSpawnsPlugin.csproj \
            --configuration Release \
            --no-restore

      - name: Publish DLL
        run: |
          dotnet publish $CsSpawnsPlugin/CsSpawnsPlugin.csproj \
            --configuration Release \
            --framework net8.0 \
            --no-restore \
            --output ./publish

      - name: Zip release artifact
        run: |
          cd publish
          zip -r publish/CsSpawnsPlugin-${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/CsSpawnsPlugin-${{ github.ref_name }}.zip